export default interface Country {
    name: string,
    topLevelDomain: [],
    alpha2Code: string,
    alpha3Code: string,
    callingCodes: [],
    capital: string,
    altSpellings: [],
    region: string,
    subregion: string,
    population: number,
    latlng: [],
    demonym: string,
    area: number,
    gini: number,
    timezones: [],
    borders: [],
    nativeName: string,
    numericCode: number,
    currencies: [],
    languages: [],
    translations:[],
    flag: string,
    regionalBlocs: [],
    cioc: string
}